######################################################################
# Automatically generated by qmake (2.01a) Mo. Mär 31 16:47:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . headers sources
INCLUDEPATH += . headers

# Input
HEADERS += headers/Canvas.hh headers/MainWindow.hh
SOURCES += main.cpp sources/Canvas.cpp sources/MainWindow.cpp
