######################################################################
# Automatically generated by qmake (2.01a) Di. Apr 1 15:43:45 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . headers sources
INCLUDEPATH += . headers

# Input
HEADERS += headers/Canvas.hh headers/MainWindow.hh
SOURCES += main.cpp sources/Canvas.cpp sources/MainWindow.cpp
