######################################################################
# Automatically generated by qmake (2.01a) Fr. Apr 4 11:31:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src/headers
INCLUDEPATH += . src/headers

# Input
HEADERS += src/headers/Canvas.hh \
           src/headers/Fractal.hh \
           src/headers/MainWindow.hh
SOURCES += main.cpp src/Canvas.cpp src/Fractal.cpp src/MainWindow.cpp
